# Generated by Django 4.2.6 on 2023-10-19 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0004_rename_e_address_extractedtext_emp_last_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extractedtext',
            old_name='name',
            new_name='f_name',
        ),
        migrations.AddField(
            model_name='extractedtext',
            name='l_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
