# Generated by Django 4.2.6 on 2023-10-19 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0005_rename_name_extractedtext_f_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractedtext',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
